"""BTC and ETH when CoinGecko refuses: the Chainlink feeds, in a fixed order.

The outage this pins down: CoinGecko's keyless `/simple/price` began answering
every caller with a CloudFront 403 HTML page while `/ping` still answered 200,
so the price tool, price alerts and ether in wallet answers all went dark.

The order: CoinGecko first only with a `COINGECKO_API_KEY`, sent as the Demo
plan header and never logged; without one, or on any CoinGecko failure, the
Chainlink feeds on Ethereum mainnet through the Infura node. Every figure is
dated by its source, a feed older than its heartbeat says it is stale, and
when both fail nothing is made up.
"""

from __future__ import annotations

from collections.abc import Callable
from datetime import UTC, datetime, timedelta
from decimal import Decimal

import httpx
import pytest
from structlog.testing import capture_logs

from chatmemory.adapters.chain import abi
from chatmemory.adapters.chain.chainlink import (
    FEEDS,
    HEARTBEAT,
    STALE_MARGIN,
    ChainlinkFeeds,
    ChainlinkUnavailable,
    is_stale,
    parse_round,
)
from chatmemory.adapters.chain.prices import CoinGeckoPrices
from chatmemory.adapters.market.alert_prices import AlertPrices
from chatmemory.adapters.market.coingecko import COINGECKO_KEY_HEADER, CoinGeckoProvider
from chatmemory.adapters.market.registration import MarketToolsConfig, build_market_tools
from chatmemory.adapters.web.limits import CallBudget, RateLimiter
from chatmemory.app.egress import MARKET_CRYPTO_PROVIDER
from chatmemory.ports.alerts import AlertState, PriceDirection, ReadFailure
from tests.e2e.harness.chain import FakeFeeds
from tests.unit.test_alert_kinds import price_alert
from tests.unit.test_market_tools import COINGECKO_OK, cleared

INFURA_KEY = "infura-secret-123"
CG_KEY = "cg-demo-secret-456"
UPDATED = 1788263940  # 2026-09-01 11:59 UTC
NOW = datetime.fromtimestamp(UPDATED, UTC) + timedelta(minutes=10)
COINGECKO_HOST = "api.coingecko.com"
MAINNET = "mainnet.infura.io"

CLOUDFRONT_403 = (
    '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">\n'
    "<HTML><HEAD><TITLE>ERROR: The request could not be satisfied</TITLE></HEAD>"
    "<BODY><H1>403 ERROR</H1><H2>The request could not be satisfied.</H2>"
    "Request blocked. We can't connect to the server for this app or website at "
    "this time.<BR clear=\"all\">Generated by cloudfront (CloudFront)</BODY></HTML>"
)
"""What the keyless price endpoint answered on 2026-09-29, from every caller."""


def refused(_: httpx.Request) -> httpx.Response:
    return httpx.Response(403, text=CLOUDFRONT_403, headers={"content-type": "text/html"})


def coingecko_ok(_: httpx.Request) -> httpx.Response:
    return httpx.Response(200, json=COINGECKO_OK)


class Edge:
    """CoinGecko and the mainnet node on one mock transport, recorded."""

    def __init__(
        self,
        coingecko: Callable[[httpx.Request], httpx.Response] = refused,
        feeds: FakeFeeds | None = None,
    ) -> None:
        self.coingecko = coingecko
        self.feeds = feeds or FakeFeeds()
        self.requests: list[httpx.Request] = []
        self.transport = httpx.MockTransport(self._handle)

    def _handle(self, request: httpx.Request) -> httpx.Response:
        self.requests.append(request)
        if request.url.host == COINGECKO_HOST:
            return self.coingecko(request)
        assert request.url.host == MAINNET, request.url.host
        return self.feeds.handle(request)

    def hosts(self) -> list[str]:
        return [r.url.host for r in self.requests]

    def coingecko_requests(self) -> list[httpx.Request]:
        return [r for r in self.requests if r.url.host == COINGECKO_HOST]


def feeds(edge: Edge, now: datetime = NOW) -> ChainlinkFeeds:
    return ChainlinkFeeds(INFURA_KEY, transport=edge.transport, clock=lambda: now)


def provider(edge: Edge, *, key: str = "", chainlink: bool = True) -> CoinGeckoProvider:
    return CoinGeckoProvider(
        CallBudget(50),
        limiter=RateLimiter(0),
        transport=edge.transport,
        api_key=key,
        chainlink=feeds(edge) if chainlink else None,
    )


async def ask(p: CoinGeckoProvider, asset: str = "BTC") -> str:
    with cleared(MARKET_CRYPTO_PROVIDER, asset, question=f"what is {asset} at?"):
        async with p.opened():
            result = await p.call_tool("crypto_price", {"asset": asset})
    assert not result.is_error, result.text
    return result.text


# --- the order ------------------------------------------------------------------


async def test_without_a_key_coingecko_is_not_asked_and_chainlink_answers() -> None:
    edge = Edge()

    text = await ask(provider(edge))

    assert edge.hosts() == [MAINNET]
    assert "Market data from Chainlink." in text
    assert "Bitcoin (BTC): 63,210.12 USD" in text
    assert "time: 2026-09-01 11:59 UTC -- quote time reported by Chainlink\n" in text
    assert "source: Chainlink https://data.chain.link/feeds/ethereum/mainnet/btc-usd" in text
    assert "stale" not in text


async def test_the_cloudfront_403_falls_back_to_chainlink() -> None:
    """The production outage, reproduced: the HTML 403 is not a price and not
    a crash, and the answer comes from the feeds."""
    edge = Edge(coingecko=refused)

    with capture_logs() as logs:
        text = await ask(provider(edge, key=CG_KEY), "ETH")

    assert edge.hosts() == [COINGECKO_HOST, MAINNET]
    assert "Ether (ETH): 2,672.57 USD" in text
    assert "quote time reported by Chainlink" in text
    [failed] = [e for e in logs if e["event"] == "market.coingecko_failed"]
    assert failed["error"] == "CoinGecko returned HTTP 403"


@pytest.mark.parametrize(
    "coingecko",
    [
        pytest.param(lambda _: httpx.Response(429, json={"status": "rate limited"}), id="429"),
        pytest.param(lambda _: httpx.Response(500, text="oops"), id="500"),
        pytest.param(lambda _: httpx.Response(200, text="<html>not json</html>"), id="html-200"),
        pytest.param(lambda _: httpx.Response(200, json={"bitcoin": {}}), id="no-price"),
        pytest.param(
            lambda r: (_ for _ in ()).throw(httpx.ConnectTimeout("slow", request=r)),
            id="timeout",
        ),
    ],
)
async def test_any_coingecko_failure_falls_back_to_chainlink(
    coingecko: Callable[[httpx.Request], httpx.Response],
) -> None:
    edge = Edge(coingecko=coingecko)

    text = await ask(provider(edge, key=CG_KEY))

    assert edge.hosts()[-1] == MAINNET
    assert "Market data from Chainlink." in text


async def test_with_a_key_a_working_coingecko_is_the_source() -> None:
    edge = Edge(coingecko=coingecko_ok)

    text = await ask(provider(edge, key=CG_KEY))

    assert edge.hosts() == [COINGECKO_HOST]
    assert "quote time reported by CoinGecko" in text


async def test_the_key_header_is_sent_only_when_a_key_is_set() -> None:
    keyed, keyless = Edge(coingecko=coingecko_ok), Edge(coingecko=coingecko_ok)

    await ask(provider(keyed, key=CG_KEY))
    # No Chainlink: the one deployment where CoinGecko is asked without a key.
    await ask(provider(keyless, chainlink=False))

    [with_key] = keyed.coingecko_requests()
    assert with_key.headers[COINGECKO_KEY_HEADER] == CG_KEY
    assert CG_KEY not in str(with_key.url), "a header, never the URL"
    [without] = keyless.coingecko_requests()
    assert COINGECKO_KEY_HEADER not in without.headers


async def test_neither_key_is_ever_logged() -> None:
    def unreachable(request: httpx.Request) -> httpx.Response:
        raise httpx.ConnectError(f"cannot reach {request.url}", request=request)

    edge = Edge(coingecko=lambda r: httpx.Response(403, text=f"denied {CG_KEY}"))
    edge.feeds.handle = unreachable  # type: ignore[method-assign]

    with (
        capture_logs() as logs,
        cleared(MARKET_CRYPTO_PROVIDER, "BTC", question="what is BTC at?"),
    ):
        result = await provider(edge, key=CG_KEY).call_tool("crypto_price", {"asset": "BTC"})

    assert result.is_error
    logged = repr(logs) + result.text
    assert CG_KEY not in logged and INFURA_KEY not in logged
    assert "***" in logged, "the Infura URL was logged, redacted"


async def test_when_both_fail_no_figure_is_made_up() -> None:
    edge = Edge(coingecko=refused)
    edge.feeds.failing = True

    with cleared(MARKET_CRYPTO_PROVIDER, "BTC", question="what is BTC at?"):
        result = await provider(edge, key=CG_KEY).call_tool("crypto_price", {"asset": "BTC"})

    assert result.is_error
    assert "No current figure is available" in result.text
    assert "USD" not in result.text.replace("CoinGecko/Chainlink", "")


async def test_one_constant_feed_request_prices_both_coins() -> None:
    """Whichever coin is asked, the same calldata leaves, and it fills both."""
    edge = Edge()
    p = provider(edge)

    await ask(p, "BTC")
    await ask(p, "ETH")

    [request] = edge.requests
    body = request.read().decode()
    assert all(f.address.removeprefix("0x") in body for f in FEEDS.values())
    other = Edge()
    await ask(provider(other), "ETH")
    assert other.requests[0].read() == request.read()


# --- decimals and staleness -------------------------------------------------------


async def test_the_answer_is_scaled_by_the_feeds_own_decimals() -> None:
    edge = Edge()
    edge.feeds.decimals = 18
    edge.feeds.prices["ETH"] = Decimal("2672.5")

    readings = await feeds(edge).read()

    assert readings["ETH"].price == Decimal("2672.5")
    assert readings["BTC"].price == Decimal("63210.12")


def test_a_round_that_never_completed_is_not_a_price() -> None:
    def word(*values: int) -> bytes:
        return bytes.fromhex("".join(abi.uint(v) for v in values))

    assert parse_round(word(8), word(1, 6_321_012_000_000, 0, UPDATED, 1)) == (
        Decimal("63210.12"),
        datetime.fromtimestamp(UPDATED, UTC),
    )
    assert parse_round(word(8), word(1, 0, 0, UPDATED, 1)) is None
    assert parse_round(word(8), word(1, -5, 0, UPDATED, 1)) is None
    assert parse_round(word(8), word(1, 5, 0, 0, 1)) is None
    assert parse_round(word(99), word(1, 5, 0, UPDATED, 1)) is None
    assert parse_round(None, word(1, 5, 0, UPDATED, 1)) is None
    assert parse_round(word(8), None) is None


def test_stale_is_past_the_heartbeat_and_its_margin() -> None:
    updated = datetime.fromtimestamp(UPDATED, UTC)
    limit = HEARTBEAT + STALE_MARGIN

    assert not is_stale(updated, updated + limit)
    assert is_stale(updated, updated + limit + timedelta(seconds=1))


async def test_a_stale_feed_says_so_in_its_time_line() -> None:
    edge = Edge()
    edge.feeds.updated_at["BTC"] = UPDATED - 2 * 3600
    later = CoinGeckoProvider(
        CallBudget(50),
        limiter=RateLimiter(0),
        transport=edge.transport,
        chainlink=feeds(edge, NOW),
    )

    btc = await ask(later, "BTC")
    eth = await ask(later, "ETH")

    assert (
        "time: 2026-09-01 09:59 UTC -- quote time reported by Chainlink; stale: older "
        "than the feed's regular update interval, so it may not be the current price"
    ) in btc
    assert "stale" not in eth


async def test_a_feed_that_answers_nothing_usable_is_unavailable() -> None:
    edge = Edge()
    edge.feeds.prices = {"BTC": Decimal(0), "ETH": Decimal(0)}

    with pytest.raises(ChainlinkUnavailable):
        await feeds(edge).read()


# --- price alerts -----------------------------------------------------------------


async def test_price_alerts_read_chainlink_when_coingecko_refuses() -> None:
    edge = Edge(coingecko=refused)
    prices = AlertPrices(provider(edge, key=CG_KEY))

    latest = await prices.latest()

    assert latest["BTC"].price == Decimal("63210.12")
    assert latest["BTC"].source == "Chainlink"
    assert latest["BTC"].as_of == datetime.fromtimestamp(UPDATED, UTC)
    assert edge.hosts() == [COINGECKO_HOST, MAINNET]


async def test_a_stale_feed_is_no_reading_for_an_alert() -> None:
    edge = Edge()
    edge.feeds.updated_at["BTC"] = UPDATED - 2 * 3600
    alert = price_alert(AlertState.BELOW, PriceDirection.ABOVE)

    observed = await AlertPrices(provider(edge)).observe([alert])

    assert isinstance(observed[alert.id], ReadFailure), (
        "an alert never fires on a price older than its heartbeat"
    )


async def test_with_every_source_down_price_alerts_count_a_failed_read() -> None:
    edge = Edge(coingecko=refused)
    edge.feeds.failing = True

    with pytest.raises(Exception):  # noqa: B017, PT011 - whichever, it is not a price
        await AlertPrices(provider(edge, key=CG_KEY)).latest()


# --- ether in wallet answers ------------------------------------------------------


async def test_wallet_ether_is_priced_by_chainlink_without_a_key() -> None:
    edge = Edge()
    prices = CoinGeckoPrices(transport=edge.transport, chainlink=feeds(edge))

    priced = await prices.usd_price("WETH")

    assert priced is not None
    assert (priced.usd, priced.source, priced.as_of) == (
        Decimal("2672.57"),
        "Chainlink",
        "2026-09-01 11:59Z",
    )
    assert edge.hosts() == [MAINNET]


async def test_wallet_ether_falls_back_when_coingecko_refuses_the_key() -> None:
    edge = Edge(coingecko=refused)
    prices = CoinGeckoPrices(transport=edge.transport, api_key=CG_KEY, chainlink=feeds(edge))

    priced = await prices.usd_price("ETH")

    assert priced is not None and priced.source == "Chainlink"
    [request] = edge.coingecko_requests()
    assert request.headers[COINGECKO_KEY_HEADER] == CG_KEY


# --- what the registry declares ----------------------------------------------------


def test_the_crypto_server_declares_the_hosts_it_reaches_and_no_key() -> None:
    def target(**config: str) -> str:
        tools = build_market_tools(MarketToolsConfig(**config))  # type: ignore[arg-type]
        [server] = [s for s in tools.servers if s.name == MARKET_CRYPTO_PROVIDER]
        return server.target

    assert target() == "https://api.coingecko.com/api/v3/simple/price"
    assert target(infura_key=INFURA_KEY) == "https://mainnet.infura.io"
    assert target(infura_key=INFURA_KEY, coingecko_api_key=CG_KEY) == (
        "https://api.coingecko.com/api/v3/simple/price,https://mainnet.infura.io"
    )
    assert INFURA_KEY not in target(infura_key=INFURA_KEY)
